# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-01-13 10:43:42
"""
import arcpy

def Model6():  # Model 6

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    LC08_L2SP_171057_20141107_20200910_02_T1_NDVI_tiff = arcpy.Raster("LC08_L2SP_171057_20141107_20200910_02_T1_NDVI.tiff")
    LC08_L2SP_170059_20141218_20200910_02_T1_NDVI_tiff = arcpy.Raster("LC08_L2SP_170059_20141218_20200910_02_T1_NDVI.tiff")
    NDVI_datewise_mosaic = "D:\\NDVI_datewise_mosaic"

    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    NDVI_date = arcpy.management.MosaicToNewRaster(input_rasters=[LC08_L2SP_171057_20141107_20200910_02_T1_NDVI_tiff, LC08_L2SP_170059_20141218_20200910_02_T1_NDVI_tiff], output_location=NDVI_datewise_mosaic, raster_dataset_name_with_extension="NDVI_date", coordinate_system_for_the_raster="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", pixel_type="16_BIT_SIGNED", cellsize=None, number_of_bands=1, mosaic_method="MEAN", mosaic_colormap_mode="FIRST")[0]
    NDVI_date = arcpy.Raster(NDVI_date)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Researcher\Documents\ArcGIS\Projects\Kenya_drought\Kenya_drought.gdb", workspace=r"C:\Users\Researcher\Documents\ArcGIS\Projects\Kenya_drought\Kenya_drought.gdb"):
        Model6()
