# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-11-19 10:06:07
"""
import arcpy

# pull all NDVI files
ndvi_path = "C:\\Tara_Fall_2019\\Kenya_Drought\\Calculated_NDVI"
import os 
ndvi_files = os.listdir(ndvi_path)
clipped_files = [file for file in ndvi_files if "CLIP" in file]

for file in clipped_files:

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")

    random_samples_2_ = "random_samples"
    tif_file = arcpy.Raster(os.path.join(ndvi_path, file))
    name = file[17:-28]

    # Process: Extract Multi Values to Points (Extract Multi Values to Points) (sa)
    random_samples = arcpy.sa.ExtractMultiValuesToPoints(in_point_features=random_samples_2_, in_rasters=[[tif_file, name]], bilinear_interpolate_values="NONE")
    .save(Extract_Multi_Values_to_Points)

