# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-02-08 10:44:56
"""
import arcpy

def Model9():  # Model 9

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")

    narok_points_ndvi_soil_lulc_2_ = "narok_points_ndvi_soil_lulc"
    awc_grass = arcpy.Raster("awc_grass")

    # Process: Extract Multi Values to Points (Extract Multi Values to Points) (sa)
    narok_points_ndvi_soil_lulc = arcpy.sa.ExtractMultiValuesToPoints(in_point_features=narok_points_ndvi_soil_lulc_2_, in_rasters=[[awc_grass, "awc_grass"]], bilinear_interpolate_values="NONE")
    .save(Extract_Multi_Values_to_Points)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Researcher\Documents\ArcGIS\Projects\Kenya_drought\Kenya_drought.gdb", workspace=r"C:\Users\Researcher\Documents\ArcGIS\Projects\Kenya_drought\Kenya_drought.gdb"):
        Model9()
